# Load Data

In [79]:
# Load the data
# data is first downloweded into DATA_PATH from 
# http://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt
import os
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

DATA_PATH = 'data'
FILE_NAME = 'train.csv'

def load_data(data_path=DATA_PATH, file_name=FILE_NAME):
    # load everything into data
    file_path = os.path.join(data_path, file_name)
    data = pd.read_csv(file_path)
    
    return data

# select all numerical columns only
def num_col(data):
    
    cols = []
    for col in data.columns:
        if data[col].dtype in [int, float, np.int64, np.float64]:
            cols.append(col)
    
    return data[cols]

def fit_nan(data):
    from sklearn.impute import SimpleImputer
    
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    return imp.fit_transform(data)
    
        
# splits data in train_data, train_label, test_data, test_label
def split_data(data, ratio=0.9):
    X = data[:,:-1]
    y = data[:,-1]
    
    size = int(X.shape[0] * ratio)
    
    return X[:size], y[:size], X[size:], y[size:]

def pipe_num_data(data_path=DATA_PATH, file_name=FILE_NAME, ratio=0.9):
    return split_data(fit_nan(num_col(load_data(data_path=data_path, file_name=file_name))), ratio)

train_data, train_label, test_data, test_label = pipe_num_data()

# Random Forest Bench Mark

In [78]:
# random forest bench mark
def bench_mark():    
    train_data, train_label, test_data, test_label = pipe_num_data()
    rf = RandomForestRegressor(n_estimators=500)
    rf.fit(train_data, train_label)
    
    ypred = rf.predict(test_data)
    
    return mean_absolute_error(ypred, test_label)
rf = RandomForestRegressor(n_estimators=300)
rf.fit(train_data, train_label)
    
ypred = rf.predict(test_data)
e = np.sqrt(mean_squared_error(np.log(ypred), np.log(test_label)))
print("Random Forest log mean root-mean-squared error is:", e)

Random Forest log mean root-mean-squared error is: 0.15855510492722855

# Bagged Linear Regression

In [76]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import BaggingRegressor

rg = LinearRegression()
lg = BaggingRegressor(rg, n_estimators=500)

lg.fit(train_data, train_label)
ypred = lg.predict(test_data)
e = np.sqrt(mean_squared_error(np.log(ypred), np.log(test_label)))
print("Random Forest log mean root-mean-squared error is:", e)

Random Forest log mean root-mean-squared error is: 0.1724670375711016

# Submittion

In [110]:
train_data, train_label, test_data, test_label = pipe_num_data(ratio=1.0)
train_data, train_label, test_data, test_label = pipe_num_data()
rf = RandomForestRegressor(n_estimators=500)
rf.fit(train_data, train_label)

submit_data = fit_nan(num_col(load_data(data_path=DATA_PATH, file_name='test.csv')))
length = submit_data.shape[0]

pred = rf.predict(submit_data)

In [112]:
submit = np.concatenate([np.arange(1461, 1461+length).reshape(length,1), pred.reshape(length, 1)])
pd.DataFrame(submit)

               0
0       1461.000
1       1462.000
2       1463.000
3       1464.000
4       1465.000
5       1466.000
6       1467.000
7       1468.000
8       1469.000
9       1470.000
10      1471.000
11      1472.000
12      1473.000
13      1474.000
14      1475.000
15      1476.000
16      1477.000
17      1478.000
18      1479.000
19      1480.000
20      1481.000
21      1482.000
22      1483.000
23      1484.000
24      1485.000
25      1486.000
26      1487.000
27      1488.000
28      1489.000
29      1490.000
...          ...
2888   82258.132
2889  138440.326
2890   72220.018
2891  115857.154
2892   63345.298
2893  298922.146
2894  277129.004
2895  197781.908
2896  146924.734
2897  230755.474
2898  160511.992
2899  198635.336
2900  186279.808
2901  336671.112
2902  350795.760
2903  115613.606
2904  200357.910
2905  118921.022
2906  128270.016
2907  140711.468
2908   85149.786
2909   85272.308
2910  154447.552
2911   89041.084
2912   82322.054
2913   85172.502
2914   86160.886
2915  164067.336
2916  114163.426
2917  233503.104

[2918 rows x 1 columns]

In [108]:
np.arange(1,3)

array([1, 2])